### PR TITLE
Single Page Application development with React and Vert.x

### PR DESCRIPTION
**Pull request by tsegismont**
Initial version

### CODE REVIEW

**Comment by tsegismont** [comment]
@pmlopes can you confirm this is inline with the process you had in mind for SPA development?

@jponge in addition to readability, can you check the Gradle config? Perhaps there are more idiomatic ways to configure:

- tasks dependencies
- copy to resources dir

Thank you both

**Review by jponge — COMMENTED** [review]
This is a very useful how-to, thanks @tsegismont 👍 

1. I would expand Java code blocks rather than have them collapsed by default. Collapsing Maven XML or Gradle descriptors is useful, but for code we can save an extra click.

2. Cool that you use `com.moowork.node` in Gradle, it really helps having a self-contained build.

3. Typo: `the creation of a new React application with reate-react-app`

4. You can ignore `.gradle/**/*` for Jekyll since there are tons of files it will try to process.

5. In Gradle you may remove the dependency on the `npmInstall` task because every compilation depends on that costly non-idempotent check. Just document that the first time it has to be called.

**Comment by tsegismont** [comment]
@jponge thank you :bowing_man: 

>    I would expand Java code blocks rather than have them collapsed by default. Collapsing Maven XML or Gradle descriptors is useful, but for code we can save an extra click.

Right. I've removed it everywhere since here we don't even show the entire POM or build file, just the dependency section.

>    Typo: the creation of a new React application with reate-react-app

Nice catch

>    You can ignore .gradle/**/* for Jekyll since there are tons of files it will try to process.

Not sure how I should do that

>    In Gradle you may remove the dependency on the npmInstall task because every compilation depends on that costly non-idempotent check. Just document that the first time it has to be called.

But then it's not equivalent to the POM file. And the idea was that a backend developer working on the app doesn't have to think about this.

**Comment by jponge** [comment]
You can ignore files in `_config.yml`, see also https://jekyllrb.com/docs/configuration/options/

The suggestion on not depending on `npminstall` is really about speeding up the compile/run cycle, but in the case of a how-to it may not be an issue.

**Comment by tsegismont** [comment]
> You can ignore files in _config.yml

Looks like it's excluded already, correct?

>The suggestion on not depending on npminstall is really about speeding up the compile/run cycle, but in the case of a how-to it may not be an issue.

Ok. We can revisit later then.

**Review by pmlopes — COMMENTED** [review]
I've a few comments on personal taste, so feel free to ignore if you disagree.

* in a project like this (frontend SPA + backend) I'd prefer to have the 2 sub projects clearly separated. (the frontend code lives inside the java project, which feels awkward for someone who will just work on the frontend)

Having the 2 projects isolated would mean that the 2 could have different lifecycles and it would speed up builds (a java build would not necessarily need a npm/cra build)

Personally I don't like the idea of a maven plugin installing npm and node, for the reason that if I'm using the CRA tool in dev mode, it's not guaranteed that their versions match, plus lots of downloads will happen on each `mvn clean` plus I'm not sure if this approach will use the npm package cache, which would mean download again and again the same packages on each clean)

**Comment by tsegismont** [comment]
Thanks for reviewing @pmlopes 

I put everything under one project and used frontend-maven-plugin/gradle-node-plugin because this is how Java developers often deal with SPA applications. Admittedly, it doesn't mean it is a good idea. But I guess there are enough backend folks scared by anything Javascript so that having a process not requiring them to install node/npm feels appealing.

What do you think @jponge ? Are you fine with removing the Maven/Gradle plugins for frontend and use npm directly?

**Comment by jponge** [comment]
I can't say for Maven, but in the case of Gradle I like having the Node plugin. It's quite flexible and the Java build delegates to the Node build.

I would also split the front and the back as separate Gradle modules, but in the case of a how-to I think it is fine to have both within the same one. We had agreed that how-tos should be minimalistic.

You can however have a note to say that in a real-world project it is cleaner to separate the front and the back.

**Comment by tsegismont** [comment]
@jponge @pmlopes I added a note about splitting frontend/backend code as the project grows. If this is fine with you let's put this on the web!

**Comment by jponge** [comment]
Good to me!

Le mar. 18 juin 2019 à 14:55, Thomas Segismont <notifications@github.com> a
écrit :

**Pull request merged**
